[build]
target = "m68k-unknown-none.json"

rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    #"-C", "linker=rust-lld",
    
    # If you run into problems, use this instead
    "-C", "linker=m68k-elf-ld",

    # Make sure the linker includes linker script
    "-C", "link-arg=-Tlink.x",
]

[unstable]
build-std = ["core"]