[package]
name = "m68k-rom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m68k-rt = { path = "../m68k-rt" }
m68k = { path = "../m68k" }
panic-abort = "0.3.2"